import type { Metadata } from 'next';
import { IconProvider } from '@/providers/Icons';
import { CostellarProvider } from '@/providers/Costellar';
import clsx from 'clsx';
import { font_body, font_title } from '@/lib/fonts';
import Animations from '@/lib/animations/lazy';
import '@/styles/globals.css';
import { UserdataProvider } from '@/providers/Userdata';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<IconProvider>
				<CostellarProvider font={clsx(font_body.variable, font_title.variable, font_body.className)}>
					<Animations>
						<UserdataProvider>{children}</UserdataProvider>
					</Animations>
				</CostellarProvider>
			</IconProvider>
		</html>
	);
}
